---
# Description
# Check for Kubernetes events
#
# Instructions
#   1. Add the "kubernetes" or "kubernetes/events" subscription to agents
#      that should run this check.
#   2. This check can either use "in cluster" (running in a contariner in
#      a Kubernetes pod) or kubeconfig style (same as kubectl) authentication
#      when connecting to the API to query events.  The default is "in cluster".
#   3. This check creates events using the Agent API, so it will need to be
#      enabled and accessible.  This is enabled on http:127.0.0.1:3031 by
#      default.
#   4. This check requires that 'stdin' be set to true as it reads in its
#      check definition to determine at what interval it is running.
#   5. More configuration options are available for this plugin; please see the
#      plugin documentation for more details.
#
# Documentation
#   - https://github.com/sensu/sensu-kubernetes-events#sensu-kubernetes-events-check
#
# Contributors
#   The following individuals have contributed to this configuration template:
#   - Todd Campbell, @nixwiz
type: CheckConfig
api_version: core/v2
metadata:
  name: sensu-kubernetes-events
spec:
  command: >-
    sensu-kubernetes-events
    --agent-api-url http://127.0.0.1:3031/events
    --event-type "!=Normal"
  runtime_assets:
    - sensu/sensu-kubernetes-events:0.1.0-alpha3
  publish: false
  subscriptions:
    - kubernetes
    - kubernetes/events
  interval: 30
  timeout: 10
  ttl: 0
  proxy_entity_name: ""
  stdin: true
  handlers:
    - alert
---
type: Asset
api_version: core/v2
metadata:
  name: sensu/sensu-kubernetes-events:0.1.0-alpha3
  labels:
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-kubernetes-events
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-kubernetes-events
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 0.1.0-alpha3
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.name: sensu-kubernetes-events
    io.sensu.bonsai.tags: check, kubernetes
spec:
    builds:
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_windows_amd64.tar.gz
      sha512: 4a47a804fa0e9a337bf9b94d4b32da97f0c0696c5fc17e9575e80707687d1ecd764eeeec10feff72e062c60babc10e3b29740a36be415b3e8d940186c77f6fae
      filters:
        - entity.system.os == 'windows'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_darwin_amd64.tar.gz
      sha512: 296dca0229ae4729db41dc5b0e8172d494b017c60822dba807fe9b7f6e19425ca1c9be4f446d32fe2b9a599b3a6674cbebcb429d0d62266d36727c7b4e8b4846
      filters:
        - entity.system.os == 'darwin'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_linux_armv7.tar.gz
      sha512: 03eb8df268f809b0838a617345ec5921c29aca51d1d3a9872ec856cbe57d5216f4d6a15338b0425381511f60f2612cdb70ac1f4c43673ca94031260c72a75a62
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'armv7'
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_linux_arm64.tar.gz
      sha512: 7db47b63208d6fd28dce8e4759908fb0e52b5d3a2d7e771e2d4a63ce3963aef300766ddd9bcfd0000203667f8877715986b989b3e18f3eae4b56d790914b5062
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'arm64'
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_linux_386.tar.gz
      sha512: 5096311a868e2ca14f37add5b896ebbd94e3b50e486e5dfbfeb89adb760adaad66703b57e173a5197ab4932595e15f6fa8d7f147e54915393b1d92cd6563245b
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == '386'
    - url: https://assets.bonsai.sensu.io/e8648ebb440f9871aa304342060785a111611ab4/sensu-kubernetes-events_0.1.0-alpha3_linux_amd64.tar.gz
      sha512: bf33d49c40851678d7d6d3948d78a57890f5a4237205c335b96efdff5b6c2daa6912f7fbe0bda4cad6814be7a1e8b16117367ee4336a0d09e634d3e30618a4aa
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'amd64'
